"""user table

Revision ID: 1a9a87107c0a
Revises: cbd009cafefd
Create Date: 2019-08-07 17:20:44.072846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9a87107c0a'
down_revision = 'cbd009cafefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_tbl', ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tbl', type_='unique')
    # ### end Alembic commands ###
