"""new fields in user model

Revision ID: 69d6bb5b01ab
Revises: 1a9a87107c0a
Create Date: 2019-08-23 10:36:19.941924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d6bb5b01ab'
down_revision = '1a9a87107c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tbl', sa.Column('user_about_me', sa.String(length=140), nullable=True))
    op.add_column('user_tbl', sa.Column('user_last_sign_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tbl', 'user_last_sign_in')
    op.drop_column('user_tbl', 'user_about_me')
    # ### end Alembic commands ###
