"""user table

Revision ID: cbd009cafefd
Revises: 
Create Date: 2019-08-07 17:15:32.000310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbd009cafefd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('user_pw', sa.String(length=94), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_profile_path', sa.String(length=255), nullable=True),
    sa.Column('user_department', sa.String(length=64), nullable=True),
    sa.Column('user_grade', mysql.TINYINT(unsigned=True, zerofill=True), nullable=True),
    sa.Column('user_gender', mysql.ENUM('M', 'F'), nullable=True),
    sa.Column('user_membership', mysql.ENUM('N', 'A'), nullable=True),
    sa.Column('user_registration_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tbl_user_id'), 'user_tbl', ['user_id'], unique=True)
    op.drop_index('idx_user_email', table_name='tbl_user')
    op.drop_index('idx_user_id', table_name='tbl_user')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('seq', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('user_pw', mysql.VARCHAR(length=94), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('user_profile_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_department', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('user_grade', mysql.TINYINT(display_width=4, unsigned=True, zerofill=True), autoincrement=False, nullable=False),
    sa.Column('user_membership', mysql.ENUM('N', 'A'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('user_gender', mysql.ENUM('M', 'F'), server_default=sa.text("'M'"), nullable=False),
    sa.Column('user_registration_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'tbl_user', ['user_id'], unique=True)
    op.create_index('idx_user_email', 'tbl_user', ['user_email'], unique=True)
    op.drop_index(op.f('ix_user_tbl_user_id'), table_name='user_tbl')
    op.drop_table('user_tbl')
    # ### end Alembic commands ###
