"""delete fields in user model

Revision ID: d1e5e8b8dd1c
Revises: 69d6bb5b01ab
Create Date: 2019-08-24 00:37:23.370491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1e5e8b8dd1c'
down_revision = '69d6bb5b01ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tbl', 'user_profile_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tbl', sa.Column('user_profile_path', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
